export enum GermanStatesEnum {
  BADEN_WUERTTEMBERG = 'baden-wuerttemberg',
  BAVARIA = 'bavaria',
  BERLIN = 'berlin',
  BRANDENBURG = 'brandenburg',
  BREMEN = 'bremen',
  HAMBURG = 'hamburg',
  HESSE = 'hesse',
  LOWER_SAXONY = 'lower-saxony',
  MECKLENBURG_VORPOMMERN = 'mecklenburg-vorpommern',
  NORTH_RHINE_WESTPHALIA = 'north-rhine-westphalia',
  RHINELAND_PALATINATE = 'rhineland-palatinate',
  SAARLAND = 'saarland',
  SAXONY = 'saxony',
  SAXONY_ANHALT = 'saxony-anhalt',
  SCHLESWIG_HOLSTEIN = 'schleswig-holstein',
  THURINGIA = 'thuringia',
}
